In [1]:
import numpy as np
import pandas as pd
from sklearn.svm import SVR
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

df = pd.read_csv(r"C:\Users\umut3\PycharmProjects\MlSelectionREG\Data.csv")

In [2]:
X = df.iloc[:, :-1].values
y = df.iloc[:, 4:].values

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

In [4]:
# Multi Linear Regression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

y_pred = regressor.predict(X_test)
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

r2_score(y_test, y_pred)

[[431.23       431.42761597]
 [460.01       458.56124622]
 [461.14       462.75264705]
 ...
 [473.26       469.51835895]
 [438.         442.41759454]
 [463.28       461.88279939]]


0.9325315554761303

In [5]:
# Polynomial Regression
pol_reg = PolynomialFeatures(degree=4)
X_pol = pol_reg.fit_transform(X_train)
lin_reg = LinearRegression()
lin_reg.fit(X_pol, y_train)

y_pred = lin_reg.predict(pol_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

r2_score(y_test, y_pred)

[[431.23 433.94]
 [460.01 457.9 ]
 [461.14 460.53]
 ...
 [473.26 469.53]
 [438.   438.27]
 [463.28 461.66]]


0.9458193819604375

In [6]:
# SVR
sc_X = StandardScaler()
sc_y = StandardScaler()
X_sc = sc_X.fit_transform(X_train)
y_sc = sc_y.fit_transform(y_train)

svr_reg = SVR(kernel="rbf")
svr_reg.fit(X_sc, y_sc.ravel())

y_pred = sc_y.inverse_transform(svr_reg.predict(sc_X.transform(X_test)).reshape(-1, 1))
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

r2_score(y_test, y_pred)

[[431.23 434.05]
 [460.01 457.94]
 [461.14 461.03]
 ...
 [473.26 470.6 ]
 [438.   439.42]
 [463.28 460.92]]


0.948078404998626

In [7]:
# Decision Tree Regression
tree_reg = DecisionTreeRegressor(random_state=0)
tree_reg.fit(X_train, y_train)

y_pred = tree_reg.predict(X_test)
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

r2_score(y_test, y_pred)

[[431.23 431.28]
 [460.01 459.59]
 [461.14 460.06]
 ...
 [473.26 471.46]
 [438.   437.76]
 [463.28 462.74]]


0.922905874177941

In [8]:
# Random Tree Regression
rnd_reg = RandomForestRegressor(random_state=0)
rnd_reg.fit(X_train, y_train.ravel())

y_pred = rnd_reg.predict(X_test)
print(np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1))

r2_score(y_test, y_pred)

[[431.23 433.64]
 [460.01 457.71]
 [461.14 463.41]
 ...
 [473.26 468.97]
 [438.   439.18]
 [463.28 461.29]]


0.9651050302169809